# Site settings
title: "New England Model Engineering Society"
description: "New England Model Engineering Society"

# Make a preview of the new site available from /new-site/

# Build settings
permalink: :title/
sass:
  sass_dir: css

